### ISSUE TITLE
Tried deploying this on vercel and its not working?

### ISSUE THREAD

**Issue by parisosuch** [joschan21/next-analytics#1]
I deployed this on vercel, with the proper env variable deployments and stuff. I even verified this by console logging the token on the vercel serverside logs and it appeared there.

However this isn't posting to the upstash db as intended. It is working on the localhost though. Any ideas?

```
try {
    analytics.track('pageview', {
        page: '/',
        country: req.geo?.country,
    }).then(() => {
        console.log("Successful track.")
    });

} catch (err) {
    // fail silently during attempt
    console.error(err)
}
```

The `Successful track.` log never appears. And there is nothing posted to the DB. There is also no error being outputted.

**Comment by parisosuch** [comment]
@joschan21 I got this working. You need to do an `await analytics.track()` in order to hold up the middle ware server side execution until the promise is fulfilled.

**Comment by joschan21** [comment]
yeah weird that this caused an issue for you, merged the PR so it should always work now 👍
